name: test
on: [push, pull_request]
env: 
  OS_HOST: localhost:9200
  OS_USER:
  OS_PASS:
  OS_INDEX: os-perl-benchmark-index
  OS_SSL: 0
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl:
          [
            "5.38",
            "5.36",
            "5.34",
            "5.32",
            "5.30",
          ]
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Install dependencies
        run: cpanm -nq --installdeps --with-develop --with-recommends .
      - name: Install Opensearch
        uses: ankane/setup-opensearch@v1
        with:
          opensearch-version: 2
      - name: Run test
        run: prove -lr t

